### ISSUE TITLE
is_desktop is not defined :(

### ISSUE THREAD

**Issue by ouzhou** [rguerreiro/express-device#44] opened 2016-08-13 12:13 UTC
it didn't work

**Comment by rguerreiro** [comment] 2016-08-23 09:40
Strange, because it's [working on the tests](https://github.com/rguerreiro/express-device/blob/master/test/app/index_helpers.ejs).

Can you please post your code that reproduces the bug?

**Comment by AuspeXeu** [comment] 2017-02-07 14:03
You need to add this line of code as explained in the documentation

`device.enableDeviceHelpers(app)`

**Comment by rguerreiro** [comment] 2018-01-13 18:11
Closing it. Feel free to comeback if the issue arises

**Closed as completed by rguerreiro** 2018-01-13 18:11 UTC
